<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'ddf6b3d362d5eac1e00550eb1e5b9875',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/ppe_db?serverVersion=10.11.2-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
